# Makefile mínimo para compilar swetest en macOS

CC = gcc
CFLAGS = -g -Wall -std=gnu99 -fPIC
LDFLAGS = -lm
SOURCES = swetest.c swedate.c swehouse.c swejpl.c swemmoon.c swemplan.c sweph.c swephlib.c swecl.c swehel.c
OBJECTS = $(SOURCES:.c=.o)
TARGET = swetest

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)
